// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: datashare.proto

#include "datashare.pb.h"
#include "datashare.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace datashare {

static const char* DataShare_method_names[] = {
  "/datashare.DataShare/SendData",
};

std::unique_ptr< DataShare::Stub> DataShare::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DataShare::Stub> stub(new DataShare::Stub(channel));
  return stub;
}

DataShare::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SendData_(DataShare_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DataShare::Stub::SendData(::grpc::ClientContext* context, const ::datashare::ClientRequest& request, ::datashare::ServerReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datashare::ClientRequest, ::datashare::ServerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendData_, context, request, response);
}

void DataShare::Stub::experimental_async::SendData(::grpc::ClientContext* context, const ::datashare::ClientRequest* request, ::datashare::ServerReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datashare::ClientRequest, ::datashare::ServerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendData_, context, request, response, std::move(f));
}

void DataShare::Stub::experimental_async::SendData(::grpc::ClientContext* context, const ::datashare::ClientRequest* request, ::datashare::ServerReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datashare::ServerReply>* DataShare::Stub::PrepareAsyncSendDataRaw(::grpc::ClientContext* context, const ::datashare::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datashare::ServerReply, ::datashare::ClientRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datashare::ServerReply>* DataShare::Stub::AsyncSendDataRaw(::grpc::ClientContext* context, const ::datashare::ClientRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

DataShare::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DataShare_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DataShare::Service, ::datashare::ClientRequest, ::datashare::ServerReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DataShare::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datashare::ClientRequest* req,
             ::datashare::ServerReply* resp) {
               return service->SendData(ctx, req, resp);
             }, this)));
}

DataShare::Service::~Service() {
}

::grpc::Status DataShare::Service::SendData(::grpc::ServerContext* context, const ::datashare::ClientRequest* request, ::datashare::ServerReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace datashare

